apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"ansible-tower"},"name":"ansible-tower","namespace":"tower371"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"ansible-tower"}},"template":{"metadata":{"labels":{"app":"ansible-tower","name":"ansible-tower-web-deploy","service":"django"}},"spec":{"containers":[{"image":"registry.redhat.io/ansible-tower-37/ansible-tower-rhel7:3.7.1","imagePullPolicy":"Always","name":"ansible-tower-web","ports":[{"containerPort":8052}],"resources":{"requests":{"cpu":"500m","memory":"1Gi"}},"volumeMounts":[{"mountPath":"/var/run/supervisor","name":"supervisor-socket"},{"mountPath":"/var/run/awx-rsyslog","name":"rsyslog-socket"},{"mountPath":"/var/lib/awx/rsyslog","name":"rsyslog-dir"},{"mountPath":"/etc/tower/settings.py","name":"ansible-tower-application-config","readOnly":true,"subPath":"settings.py"},{"mountPath":"/etc/nginx/nginx.conf","name":"ansible-tower-nginx-config","readOnly":true,"subPath":"nginx.conf"},{"mountPath":"/etc/tower/conf.d/","name":"ansible-tower-application-credentials","readOnly":true},{"mountPath":"/usr/bin/launch_awx.sh","name":"ansible-tower-launch-awx-web","readOnly":true,"subPath":"launch_awx.sh"},{"mountPath":"/usr/bin/launch_awx_task.sh","name":"ansible-tower-launch-awx-task","readOnly":true,"subPath":"launch_awx_task.sh"},{"mountPath":"/supervisor.conf","name":"ansible-tower-supervisor-web-config","readOnly":true,"subPath":"supervisor.conf"},{"mountPath":"/supervisor_task.conf","name":"ansible-tower-supervisor-task-config","readOnly":true,"subPath":"supervisor_task.conf"},{"mountPath":"/etc/tower/SECRET_KEY","name":"ansible-tower-secret-key","readOnly":true,"subPath":"SECRET_KEY"},{"mountPath":"/var/run/redis","name":"ansible-tower-redis-socket"},{"mountPath":"/var/run/memcached","name":"ansible-tower-memcached-socket"}]},{"command":["/usr/bin/launch_awx_task.sh"],"env":[{"name":"SUPERVISOR_WEB_CONFIG_PATH","value":"/supervisor.conf"},{"name":"AWX_SKIP_MIGRATIONS","value":"1"},{"name":"MY_POD_UID","valueFrom":{"fieldRef":{"fieldPath":"metadata.uid"}}},{"name":"MY_POD_IP","valueFrom":{"fieldRef":{"fieldPath":"status.podIP"}}}],"image":"registry.redhat.io/ansible-tower-37/ansible-tower-rhel7:3.7.1","imagePullPolicy":"Always","name":"ansible-tower-task","resources":{"requests":{"cpu":"1500m","memory":"2Gi"}},"securityContext":{"privileged":true},"volumeMounts":[{"mountPath":"/var/run/supervisor","name":"supervisor-socket"},{"mountPath":"/var/run/awx-rsyslog","name":"rsyslog-socket"},{"mountPath":"/var/lib/awx/rsyslog","name":"rsyslog-dir"},{"mountPath":"/etc/tower/settings.py","name":"ansible-tower-application-config","readOnly":true,"subPath":"settings.py"},{"mountPath":"/etc/tower/conf.d/","name":"ansible-tower-application-credentials","readOnly":true},{"mountPath":"/usr/bin/launch_awx.sh","name":"ansible-tower-launch-awx-web","readOnly":true,"subPath":"launch_awx.sh"},{"mountPath":"/usr/bin/launch_awx_task.sh","name":"ansible-tower-launch-awx-task","readOnly":true,"subPath":"launch_awx_task.sh"},{"mountPath":"/supervisor.conf","name":"ansible-tower-supervisor-web-config","readOnly":true,"subPath":"supervisor.conf"},{"mountPath":"/supervisor_task.conf","name":"ansible-tower-supervisor-task-config","readOnly":true,"subPath":"supervisor_task.conf"},{"mountPath":"/etc/tower/SECRET_KEY","name":"ansible-tower-secret-key","readOnly":true,"subPath":"SECRET_KEY"},{"mountPath":"/var/run/redis","name":"ansible-tower-redis-socket"},{"mountPath":"/var/run/memcached","name":"ansible-tower-memcached-socket"}]},{"args":["redis-server","/etc/redis.conf"],"image":"registry.redhat.io/rhscl/redis-5-rhel7:latest","imagePullPolicy":"Always","name":"ansible-tower-redis","resources":{"requests":{"cpu":"500m","memory":"2Gi"}},"volumeMounts":[{"mountPath":"/etc/redis.conf","name":"ansible-tower-redis-config","readOnly":true,"subPath":"redis.conf"},{"mountPath":"/var/run/redis","name":"ansible-tower-redis-socket"}]},{"command":["memcached","-s","/var/run/memcached/memcached.sock","-a","0666"],"image":"registry.redhat.io/ansible-tower-37/ansible-tower-memcached-rhel7:latest","imagePullPolicy":"Always","name":"ansible-tower-memcached","resources":{"requests":{"cpu":"500m","memory":"1Gi"}},"volumeMounts":[{"mountPath":"/var/run/memcached","name":"ansible-tower-memcached-socket"}]}],"securityContext":{"fsGroup":0},"serviceAccountName":"awx","terminationGracePeriodSeconds":10,"volumes":[{"emptyDir":{},"name":"supervisor-socket"},{"emptyDir":{},"name":"rsyslog-socket"},{"emptyDir":{},"name":"rsyslog-dir"},{"configMap":{"items":[{"key":"ansible-tower_settings","path":"settings.py"}],"name":"ansible-tower-config"},"name":"ansible-tower-application-config"},{"configMap":{"items":[{"key":"ansible-tower_nginx_conf","path":"nginx.conf"}],"name":"ansible-tower-config"},"name":"ansible-tower-nginx-config"},{"configMap":{"items":[{"key":"ansible-tower_redis_conf","path":"redis.conf"}],"name":"ansible-tower-config"},"name":"ansible-tower-redis-config"},{"name":"ansible-tower-application-credentials","secret":{"items":[{"key":"credentials_py","path":"credentials.py"},{"key":"environment_sh","path":"environment.sh"}],"secretName":"ansible-tower-secrets"}},{"configMap":{"defaultMode":493,"items":[{"key":"launch-awx-web","path":"launch_awx.sh"}],"name":"ansible-tower-launch-awx"},"name":"ansible-tower-launch-awx-web"},{"configMap":{"defaultMode":493,"items":[{"key":"launch-awx-task","path":"launch_awx_task.sh"}],"name":"ansible-tower-launch-awx"},"name":"ansible-tower-launch-awx-task"},{"configMap":{"items":[{"key":"supervisor-web-config","path":"supervisor.conf"}],"name":"ansible-tower-supervisor-config"},"name":"ansible-tower-supervisor-web-config"},{"configMap":{"items":[{"key":"supervisor-task-config","path":"supervisor_task.conf"}],"name":"ansible-tower-supervisor-config"},"name":"ansible-tower-supervisor-task-config"},{"name":"ansible-tower-secret-key","secret":{"items":[{"key":"secret_key","path":"SECRET_KEY"}],"secretName":"ansible-tower-secrets"}},{"emptyDir":{},"name":"ansible-tower-redis-socket"},{"emptyDir":{},"name":"ansible-tower-memcached-socket"}]}}}}
  creationTimestamp: "2020-07-25T05:23:38Z"
  generation: 1
  labels:
    app: ansible-tower
  name: ansible-tower
  namespace: tower371
  resourceVersion: "2160215"
  selfLink: /apis/apps/v1/namespaces/tower371/deployments/ansible-tower
  uid: 4ad86997-b34d-4fa3-ad85-430626dfc90e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ansible-tower
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ansible-tower
        name: ansible-tower-web-deploy
        service: django
    spec:
      containers:
      - image: registry.redhat.io/ansible-tower-37/ansible-tower-rhel7:3.7.1
        imagePullPolicy: Always
        name: ansible-tower-web
        ports:
        - containerPort: 8052
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/supervisor
          name: supervisor-socket
        - mountPath: /var/run/awx-rsyslog
          name: rsyslog-socket
        - mountPath: /var/lib/awx/rsyslog
          name: rsyslog-dir
        - mountPath: /etc/tower/settings.py
          name: ansible-tower-application-config
          readOnly: true
          subPath: settings.py
        - mountPath: /etc/nginx/nginx.conf
          name: ansible-tower-nginx-config
          readOnly: true
          subPath: nginx.conf
        - mountPath: /etc/tower/conf.d/
          name: ansible-tower-application-credentials
          readOnly: true
        - mountPath: /usr/bin/launch_awx.sh
          name: ansible-tower-launch-awx-web
          readOnly: true
          subPath: launch_awx.sh
        - mountPath: /usr/bin/launch_awx_task.sh
          name: ansible-tower-launch-awx-task
          readOnly: true
          subPath: launch_awx_task.sh
        - mountPath: /supervisor.conf
          name: ansible-tower-supervisor-web-config
          readOnly: true
          subPath: supervisor.conf
        - mountPath: /supervisor_task.conf
          name: ansible-tower-supervisor-task-config
          readOnly: true
          subPath: supervisor_task.conf
        - mountPath: /etc/tower/SECRET_KEY
          name: ansible-tower-secret-key
          readOnly: true
          subPath: SECRET_KEY
        - mountPath: /var/run/redis
          name: ansible-tower-redis-socket
        - mountPath: /var/run/memcached
          name: ansible-tower-memcached-socket
      - command:
        - /usr/bin/launch_awx_task.sh
        env:
        - name: SUPERVISOR_WEB_CONFIG_PATH
          value: /supervisor.conf
        - name: AWX_SKIP_MIGRATIONS
          value: "1"
        - name: MY_POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: registry.redhat.io/ansible-tower-37/ansible-tower-rhel7:3.7.1
        imagePullPolicy: Always
        name: ansible-tower-task
        resources:
          requests:
            cpu: 100m
            memory: 2Gi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/supervisor
          name: supervisor-socket
        - mountPath: /var/run/awx-rsyslog
          name: rsyslog-socket
        - mountPath: /var/lib/awx/rsyslog
          name: rsyslog-dir
        - mountPath: /etc/tower/settings.py
          name: ansible-tower-application-config
          readOnly: true
          subPath: settings.py
        - mountPath: /etc/tower/conf.d/
          name: ansible-tower-application-credentials
          readOnly: true
        - mountPath: /usr/bin/launch_awx.sh
          name: ansible-tower-launch-awx-web
          readOnly: true
          subPath: launch_awx.sh
        - mountPath: /usr/bin/launch_awx_task.sh
          name: ansible-tower-launch-awx-task
          readOnly: true
          subPath: launch_awx_task.sh
        - mountPath: /supervisor.conf
          name: ansible-tower-supervisor-web-config
          readOnly: true
          subPath: supervisor.conf
        - mountPath: /supervisor_task.conf
          name: ansible-tower-supervisor-task-config
          readOnly: true
          subPath: supervisor_task.conf
        - mountPath: /etc/tower/SECRET_KEY
          name: ansible-tower-secret-key
          readOnly: true
          subPath: SECRET_KEY
        - mountPath: /var/run/redis
          name: ansible-tower-redis-socket
        - mountPath: /var/run/memcached
          name: ansible-tower-memcached-socket
      - args:
        - redis-server
        - /etc/redis.conf
        image: registry.redhat.io/rhscl/redis-5-rhel7:latest
        imagePullPolicy: Always
        name: ansible-tower-redis
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/redis.conf
          name: ansible-tower-redis-config
          readOnly: true
          subPath: redis.conf
        - mountPath: /var/run/redis
          name: ansible-tower-redis-socket
      - command:
        - memcached
        - -s
        - /var/run/memcached/memcached.sock
        - -a
        - "0666"
        image: registry.redhat.io/ansible-tower-37/ansible-tower-memcached-rhel7:latest
        imagePullPolicy: Always
        name: ansible-tower-memcached
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/memcached
          name: ansible-tower-memcached-socket
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 0
      serviceAccount: awx
      serviceAccountName: awx
      terminationGracePeriodSeconds: 10
      volumes:
      - emptyDir: {}
        name: supervisor-socket
      - emptyDir: {}
        name: rsyslog-socket
      - emptyDir: {}
        name: rsyslog-dir
      - configMap:
          defaultMode: 420
          items:
          - key: ansible-tower_settings
            path: settings.py
          name: ansible-tower-config
        name: ansible-tower-application-config
      - configMap:
          defaultMode: 420
          items:
          - key: ansible-tower_nginx_conf
            path: nginx.conf
          name: ansible-tower-config
        name: ansible-tower-nginx-config
      - configMap:
          defaultMode: 420
          items:
          - key: ansible-tower_redis_conf
            path: redis.conf
          name: ansible-tower-config
        name: ansible-tower-redis-config
      - name: ansible-tower-application-credentials
        secret:
          defaultMode: 420
          items:
          - key: credentials_py
            path: credentials.py
          - key: environment_sh
            path: environment.sh
          secretName: ansible-tower-secrets
      - configMap:
          defaultMode: 493
          items:
          - key: launch-awx-web
            path: launch_awx.sh
          name: ansible-tower-launch-awx
        name: ansible-tower-launch-awx-web
      - configMap:
          defaultMode: 493
          items:
          - key: launch-awx-task
            path: launch_awx_task.sh
          name: ansible-tower-launch-awx
        name: ansible-tower-launch-awx-task
      - configMap:
          defaultMode: 420
          items:
          - key: supervisor-web-config
            path: supervisor.conf
          name: ansible-tower-supervisor-config
        name: ansible-tower-supervisor-web-config
      - configMap:
          defaultMode: 420
          items:
          - key: supervisor-task-config
            path: supervisor_task.conf
          name: ansible-tower-supervisor-config
        name: ansible-tower-supervisor-task-config
      - name: ansible-tower-secret-key
        secret:
          defaultMode: 420
          items:
          - key: secret_key
            path: SECRET_KEY
          secretName: ansible-tower-secrets
      - emptyDir: {}
        name: ansible-tower-redis-socket
      - emptyDir: {}
        name: ansible-tower-memcached-socket
status:
  conditions:
  - lastTransitionTime: "2020-07-25T05:23:38Z"
    lastUpdateTime: "2020-07-25T05:23:38Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2020-07-25T05:23:38Z"
    lastUpdateTime: "2020-07-25T05:23:38Z"
    message: ReplicaSet "ansible-tower-c849cf8b7" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
